# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "capistrano", "~> 3.11"
gem "capistrano-bundler"
gem "capistrano-rails"
gem "capistrano-rbenv"
gem "capistrano-scm-copy", "~> 0.7.0"
gem "capistrano3-unicorn"
gem "rails", "~> 6.0.0"
gem "sqlite3", "~> 1.4.1"
gem "unicorn"
